

spring:
  kafka:
    bootstrap-servers: pkc-qg8rv.ap-south-2.aws.confluent.cloud:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.springproj.journalApp.model

    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: >
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username= ***REMOVED***
            password= ***REMOVED***
      session:
        timeout:
          ms: 45000

  redis:
    uri: redis://default:***REMOVED***@redis-19917.c305.ap-south-1-1.ec2.cloud.redislabs.com:19917

  data:
    mongodb:
      uri: mongodb+srv://***REMOVED***:***REMOVED***@cluster0.z9pqr6d.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: suyashchamoli1@gmail.com
    password: ***REMOVED***
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    context-path: /journal

logging:
  level:
    net:
      SPRING BOOT:
        journalApp: DEBUG

weather:
  api:
    key: ***REMOVED***
